services:
  mjakazi-connect:
    image: ghcr.io/m6o4solutions/mjakazi-connect-project:latest
    container_name: mjakazi-connect
    restart: unless-stopped
    networks:
      - traefik-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mjakazi-connect.rule=Host(`mjakaziconnect.co.ke`) || Host(`www.mjakaziconnect.co.ke`)"
      - "traefik.http.routers.mjakazi-connect.entrypoints=websecure"
      - "traefik.http.routers.mjakazi-connect.tls.certresolver=letsencrypt"
      - "traefik.http.services.mjakazi-connect.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
    name: traefik-network
